# Docker Compose is a tool to build and run multi-container apps
# Services are the components of the App - each Service corresponds to an Image
# Docker Compose can only run on one machine. It cannot run on a Cluster.
# Docker Swarm runs on a Cluster.
# docker-compose up -d
# docker-compose down
# docker-compose logs
# docker-compose build
# docker network ls
# docker network inspect <network name>

version: "3"

services:
  wordpress:
    image: wordpress:4.9.4-php7.2-apache
    environment:
      - WORDPRESS_DB_USER=wp_user
      - WORDPRESS_DB_PASSWORD=wp_password
    ports:
      - 8080:80
    networks:
      - wordpressnet
    volumes:
      - wordpressdata:/var/www/html

  mysql:
    image: mariadb:10.3.3
    environment:
      - MYSQL_ROOT_PASSWORD=db_password
      - MYSQL_USER=wp_user
      - MYSQL_PASSWORD=wp_password
      - MYSQL_DATABASE=wordpress
    networks:
      - wordpressnet
    volumes:
      - mariadbdata:/var/lib/mysql

networks:
  wordpressnet:
    driver: bridge

volumes:
  wordpressdata:
  mariadbdata:
